### ISSUE TITLE
SIGABRT 

### ISSUE THREAD

**Issue by colemanbroad** [maweigert/spimagine#12]
870MB of 'tif' images across 30 timepoints. i call `spimagine $foldername` and the movie plays a bit then crashes:

```bash
<pyopencl.Device 'Iris Pro' on 'Apple' at 0x1024500>
/usr/local/lib/python2.7/site-packages/pyopencl/__init__.py:63: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
<pyopencl.Device 'GeForce GT 750M' on 'Apple' at 0x1022700>
/usr/local/lib/python2.7/site-packages/pyopencl/reduction.py:196: UserWarning: Reduction might be unnecessarily slow: can't query SIMD group size
  warn("Reduction might be unnecessarily slow: "
corrupted page
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spimagine/gui/glwidget.py", line 350, in dataPosChanged
    self.renderer.update_data(self.dataModel[pos])
  File "/usr/local/lib/python2.7/site-packages/spimagine/models/data_model.py", line 608, in __getitem__
    newdata = self.dataContainer[pos]
  File "/usr/local/lib/python2.7/site-packages/spimagine/models/data_model.py", line 264, in __getitem__
    return data
UnboundLocalError: local variable 'data' referenced before assignment
fish: 'spimagine t2/signal/TrueImage/' terminated by signal SIGABRT (Abort)
```

**Comment by maweigert** [comment]
For the record:

> corrupted page
> Traceback (most recent call last):

indicated that one of the tif files was having problems. So the issue was corrupted data. Probably a better error message in those cases would be helpful.
