### ISSUE TITLE
ASSERTION FAILED: scalarMap.find(key) != scalarMap.end()

### ISSUE THREAD

**Issue by paulmueller** [maweigert/spimagine#3]
Do you see anything in this commit:

https://github.com/maweigert/spimagine/commit/ec168df59f18915390bc43d58c0452fe018333c6

that might cause the following error?

```
ASSERTION FAILED: scalarMap.find(key) != scalarMap.end()
  at file /home/paul/repos/beignet/backend/src/llvm/llvm_gen_backend.cpp, function gbe::ir::Register gbe::RegisterTranslator::getScalar(llvm::Value*, uint32_t), line 417
Trace/breakpoint trap (core dumped)
```

Before (when commenting out the lines mentioned in issue #1), everything worked fine.

**Comment by paulmueller** [comment]
The mentioned commit seemed to have broken spimagine on Ubuntu. On my machine with an Nvidia GPU, I get the following error after pulling this commit:

```
python -m spimagine
could not open /home/paul/.spimagine
spimagine/lib/czifile.py:123: UserWarning: failed to import the optional _czifile C extension module.
Decoding of JXR and JPG encoded images will be unavailable.
Czifile.pyx can be obtained at http://www.lfd.uci.edu/~gohlke/
  "failed to import the optional _czifile C extension module.\n"
No module named libtiff
INFO:PyOCL.OCLProcessor | using device: GeForce GTX 560 Ti
could not import libtiff
could not import imgtools or lucy_richardson module
INFO:PyOCL.OCLProcessor | using device: GeForce GTX 560 Ti
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/paul/repos/spimagine/spimagine/__main__.py", line 5, in <module>
    main()
  File "spimagine/spimagine_gui.py", line 41, in main
    win = MainWidget()
  File "spimagine/gui_mainwidget.py", line 96, in __init__
    self.glWidget = GLWidget(self)
  File "spimagine/gui_glwidget.py", line 269, in __init__
    self.renderer = VolumeRenderer((spimagine.__DEFAULTWIDTH__,spimagine.__DEFAULTWIDTH__))
  File "spimagine/volume_render.py", line 104, in __init__
    "-cl-fast-relaxed-math -cl-unsafe-math-optimizations -cl-mad-enable")
  File "/home/paul/spimagine/env/local/lib/python2.7/site-packages/PyOCL/OCLProcessor.py", line 235, in __init__
    self.compileKernel(open(kernelFileName).read(),options=options)
  File "/home/paul/spimagine/env/local/lib/python2.7/site-packages/PyOCL/OCLProcessor.py", line 241, in compileKernel
    self.prg = cl.Program(self.clDev.context,kernelStr).build(options=options)
  File "/home/paul/spimagine/env/local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 218, in build
    options=options, source=self._source)
  File "/home/paul/spimagine/env/local/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 258, in _build_and_catch_errors
    raise err
pyopencl.RuntimeError: clBuildProgram failed: invalid binary - 

Build on <pyopencl.Device 'GeForce GTX 560 Ti' on 'NVIDIA CUDA' at 0x2283de0>:

ptxas application ptx input, line 7881; error   : Call has wrong number of parameters
ptxas application ptx input, line 8508; error   : Call has wrong number of parameters
ptxas application ptx input, line 9634; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors

(options: -cl-fast-relaxed-math -cl-unsafe-math-optimizations -cl-mad-enable -I /home/paul/spimagine/env/lib/python2.7/site-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/cl)
(source saved as /tmp/tmprat9MG.cl)
```

**Comment by maweigert** [comment]
Works fine here (ubuntu 14.04)
You still get the error with the latest branch (master or develop)?

**Comment by paulmueller** [comment]
No, works again. Thanks.
